
deps = {
    "third_party/libpng": {
        "type": "git",
        "url": "https://github.com/pnggroup/libpng.git",
        "ignore_in_git": True,
        "commit": "f5e92d76973a7a53f517579bc95d61483bf108c0",
    },
    "third_party/libjpeg-turbo": {
        "type": "git",
        "url": "https://github.com/libjpeg-turbo/libjpeg-turbo.git",
        "ignore_in_git": True,
        "commit": "f29eda648547b36aa594c4116c7764a6c8a079b9",
    },
}