name: install common dependencies

description: sync source and binary dependencies via habitat

inputs:
  concurrency:
    description: concurrency of requests
    default: '2'
    required: false
  cache-backend:
    description: cache backend for habitat
    default: 'lynx-infra'
    required: false
  target:
    description: habitat target
    default: ''
    required: false
  # actions/cache stores files with relative directory, which causes inconsistency between self-hosted runner and
  # container runner. Therefore, add this temporary option to modify cache key prefix as a workaround. Delete this when
  # we are able to adjust the container runner's directory structure to the same as self-hosted runner.
  cache-key-prefix:
    description: cache key prefix for cache action
    default: ''
    required: false

runs:
  using: composite
  steps:
    - name: setup cache action
      if: ${{ inputs.cache-backend == 'lynx-infra' }}
      uses: lynx-infra/cache@5c6160a6a4c7fca80a2f3057bb9dfc9513fcb732
      with:
        path: ~/.habitat_cache
        key: hab${{ inputs.cache-key-prefix }}-${{ runner.os }}-${{ hashFiles('./.habitat', './hab/DEPS', './hab/DEPS.ci', './hab/DEPS.dev', './hab/DEPS.module') }}
        restore-keys: |
          hab${{ inputs.cache-key-prefix }}-${{ runner.os }}-

    - name: run habitat sync
      shell: bash
      run: |
        tools/hab sync . --target dev,module,ci
